naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    # ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    ignoreCompanionObjectPropertyDeclaration: true

  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']

complexity:
  LongParameterList:
    functionThreshold: 15
    ignoreDefaultParameters: true

  LongMethod:
    active: true
    threshold: 100

  TooManyFunctions:
    active: true
    thresholdInFiles: 25
    thresholdInClasses: 25
    thresholdInInterfaces: 25
    thresholdInObjects: 25
    thresholdInEnums: 25
    ignoreDeprecated: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'Throwable'
      - 'RuntimeException'
